package com.letv.common;

public class IntentConstants {
	public static final String GoogleSearch = "com.google.android.katniss/.search.SearchActivity";
	public static final String TVlive = "com.letv.android.tv.letvlive/com.letv.android.letvlive.LiveActivity";
	public static final String LeAccount ="com.stv.t2.account/.activity.AccountGuideActivity";
	public static final String Browser = "com.android.browser/.LoadingActivity";
	public static final String Filemanager = "com.stv.filemanager/.activities.FileExplorerTabActivity";
	public static final String Feedback = "com.stv.feedback/.FeedbackActivity";
	public static final String Camera = "com.stv.camera/.CameraActivity";
	public static final String Channel = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW24";
	public static final String HDMI1 = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW26";
	public static final String HDMI2 = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW28";
	public static final String HDMI3 = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW30";
	public static final String HDMI4 = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW32";
	public static final String Settings = "com.android.tv.settings/.MainSettings";
	public static final String SystemUpdate = "com.stv.systemupgrade/.SystemUpgradeActivity";
	public static final String Component = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW34";
	public static final String Composite = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW36";
	public static final String VGA = "com.android.tv/.MainActivity -d dat=content://android.media.tv/passthrough/com.mstar.android.tv.inputservice/.HdmiInputService/HW38";
	public static final String GooglePlayMovies = "com.google.android.videos/.tv.presenter.activity.TvLauncherActivity";
	public static final String YouTuBe = "com.google.android.youtube.tv/com.google.android.apps.youtube.tv.activity.TvGuideActivity";
	public static final String GooglePlayGames = "com.google.android.play.games/com.google.android.gms.games.pano.activity.MainPanoActivity";
	public static final String GooglePlayMusic = "com.google.android.music/com.android.music.activitymanagement.TopLevelActivity";
	public static final String GooglePlayStore = "com.android.vending/com.google.android.finsky.activities.TvMainActivity";
	public static final String LeTv = "com.letv.tv/.player.PlayActivity";
	public static final String LeStore = "com.letv.tvos.appstore/.appmodule.loading.LoadingActivity";
	public static final String GameCenter = "com.letv.tvos.gamecenter/.SplashActivity";
	public static final String GunGame = "cn.tvplay.bladeletv/.ProxyActivity";
	public static final String HomeTime = "com.stv.android.videochat/.entrance.MainPageActivity";
	public static final String Message = "com.stv.message/.MainActivity";
	public static final String Calendar = "com.stv.calendar/.activity.CalendarActivity";
	public static final String Download = "com.stv.downloads/.activity.DownloadActivity";
	public static final String TvManager = "com.stv.helper.main/.LetvHelperActivity";
	public static final String LeSearh = "com.letv.leso/.WelcomeActivity";
	public static final String Music = "com.stv.music/.MainActivity";
	public static final String Help = "com.stv.userguider/.ViewPageActivity";
	public static final String Weather = "com.stv.weather/.WeatherActivity";
	public static final String WeatherCIBN = "sina.mobile.tianqitongstv/.ui.activity.MainActivity";
	public static final String Upgrade = "com.stv.systemupgrade/.SystemUpgradeActivity";
	public static final String PlayHistory = "com.stv.videohistory/.MainActivity";
	public static final String LeCloud = "com.letv.lecloud.disk/.activity.SplashActivity";
	public static final String Gallery = "com.android.gallery3d/.app.Gallery";
	public static final String LeFans = "com.jiajia.yundonghui.letv/.Start";
	public static final String CarGod = "com.coco.entertainment.immortalracer.baidutv/com.ege.android.AndroidActivity";
	public static final String Warria = "com.vwoof.tvgame.kaijia/.Demo";
	public static final String DuoLe = "com.duole.tvmgrserver/.AppStartActivity";
	public static final String Inotice = "com.android.yes2metodolist/.Main";
	public static final String LeSports = "com.lesports.tv/.business.start.WelcomeActivity";
	public static final String Shop = "com.stv.shopping/.activity.ShoppingActivity";
	public static final String Voice = "com.stv.voice/.MainActivity";
	public static final String Housekeeper = "com.stv.helper.main/.LetvHelperActivity";
	public static final String LeSo = "com.letv.leso/.activity.HomeActivity";
	public static final String CIBN = "cn.cibntv.ott/.activity.MainActivity";
	public static final String Tianqi = "com.miui.weather2/.ActivityWeatherMain";
	public static final String Cinemas = "com.golive.letvcinema/.MainActivity";
	public static final String Tool = "com.stv.message/.MainActivity";
	public static final String ChildrenTV ="com.letv.tv/letv.plugin.framework.activity.HostActivity";
}
